name: Scheduled Jobs

on:
  schedule:
    - cron: '20 * * * *'
  workflow_dispatch:
    inputs:
      name:
        description: "Person"
        required: true
        default: "kyj"
      home:
        description: "location"
        required: false
        default: "GitHubActions"

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: echo repository name
        run: echo "${{ github.repository }}"

      - name: repository checkout
        uses: actions/checkout@v3 # https://github.com/actions/checkout
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          path: GitHubActions

      - name: Add date and push
        run: |
          cd GitHubActions
          if [ ! -d auto-commit ]; then
            mkdir auto-commit
          fi
          cd auto-commit
          sudo timedatectl set-timezone Asia/Seoul
          date >> $(date "+%Y-%m-%d %I시 %M분 %S초").txt
          git add .
          git config --global user.email "uni0125@naver.com"
          git config --global user.name "kyj"
          git commit -am "$(date) commit and push"
          git push
