name: Scheduled Jobs

on:
  schedule:
    - cron: '20 * * * *'
  workflow_dispatch:
    inputs:
      name:
        description: "Person"
        required: true
        default: "kyj"
      home:
        description: "location"
        required: false
        default: "GitHubActions"

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: echo repository name
        run: echo "${{ github.repository }}"

      - name: repository checkout
        uses: actions/checkout@v3 # https://github.com/actions/checkout
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          path: GitHubActions

      - name: Add date and push
        run: |
          cd GitHubActions
          
          MAIN_FOLDER="auto-commit"
          if [ ! -d "$MAIN_FOLDER" ]; then
            mkdir "$MAIN_FOLDER"
          fi
          cd "$MAIN_FOLDER"
          
          YEAR=$(date "+%Y")
          if [ ! -d "$YEAR" ]; then
            mkdir "$YEAR"
          fi
          cd "$YEAR"
          
          MONTH=$(date "+%m")
          if [ ! -d "$MONTH" ]; then
            mkdir "$MONTH"
          fi
          cd "$MONTH"
          
          DAY=$(date "+%d")
          if [ ! -d "$DAY" ]; then
            mkdir "$DAY"
          fi
          cd "$DAY"
          
          sudo timedatectl set-timezone Asia/Seoul
          
          echo $(date)
          NOW=$(date "+%Y-%m-%d_%H시_%M분_%S초")
          date >> "$NOW".txt
          
          git add .
          git config --global user.email "uni0125@naver.com"
          git config --global user.name "kyj"
          git commit -am "$NOW commit and push"
          git push
